version: "3"

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=<claimToken>
      - ADVERTISE_IP=http://192.168.1.152:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
    hostname: PlexServerDocker
    volumes:
      - nfs-plex:/config
      - nfs-plextrans:/transcode
      - nfs-plexmedia:/data
    restart: unless-stopped
    network_mode: bridge

volumes:
  nfs-plex:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.5,nolock,soft,nfsvers=4"
      device: ":/mnt/pool-600gb/share/portainer-data/plex"
  nfs-plextrans:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.5,nolock,soft,nfsvers=4"
      device: ":/mnt/pool-600gb/share/portainer-data/plex/transcodes"
  nfs-plexmedia:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.5,nolock,soft,nfsvers=4"
      device: ":/mnt/pool-600gb/plex-media"
