version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /var/tndata/sabnzbd:/config
      - /var/tndata/sabnzbd/downloads:/downloads #optional
      - /var/tndata/sabnzbd/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    network_mode: bridge
