version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TZ=America/Los_Angeles
    volumes:
      - portainer_data/sonarr:/config
      - portainer_data/tvseries:/tv
      - portainer_data/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

volumes:
  portainer_data:
    name: truenasData
    external: true
