version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TZ=America/Los_Angeles
    volumes:
      - nfs-sonarr:/config
      #- nfs-sonarrtv:/tv
      #- nfs-sonarr/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

volumes:
  nfs-sonarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.5,nolock,soft,nfsvers=4"
      device: ":/mnt/pool-600gb/share/portainer-data/sonarr"
      
